FileVersion = 1

[Project]
Name = "msgpackc-beef"
DefaultNamespace = "msgpackc"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\msgpackc_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\msgpackc.lib"]
